DOCSP-43525 - Decimal128
mongodb/docs-csharp pull request #240
Opened 2024-09-26 14:58 UTC by mongoKart

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-golang/blob/master/REVIEWING.md)

JIRA - https://jira.mongodb.org/browse/DOCSP-43525

### Staging Links

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?
- [x] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-09-26 15:33 UTC, rustagir requested changes
few small things

2024-09-26 15:33 UTC, rustagir commented on source/upgrade.txt
> +- In previous versions of the driver, if a field had the C# data type ``Decimal128`` or
```suggestion
- In previous versions of the driver, if a field had a value of {+language+} data type ``Decimal128`` or
```

2024-09-26 15:33 UTC, rustagir commented on source/upgrade.txt
> +  values instead.
S: flip these sentence around eg

> Serializes {+language+} ``Decimal128`` values as BSON ``Decimal128`` values. In prev versions...

2024-09-26 15:33 UTC, rustagir commented on source/upgrade.txt
> +  apply the ``[BsonRepresentation(BsonType.String)]`` attribute to the field.
```suggestion
  To serialize a ``decimal`` or ``Decimal128`` value as a string,
  apply the ``[BsonRepresentation(BsonType.String)]`` attribute to the field.
```

2024-09-26 15:33 UTC, rustagir commented on source/upgrade.txt
> +  apply the ``[BsonRepresentation(BsonType.String)]`` attribute to the field.
S: Instead of boradly linking to the serialization guide, consider linking to the bsonrepresentation attribute content

2024-09-27 15:03 UTC, rustagir approved these changes
lgtm

2024-09-27 15:03 UTC, rustagir commented on source/upgrade.txt
> +  apply the ``[BsonRepresentation(BsonType.String)]`` attribute to the field.
S: fix line wrapping

2024-10-01 06:18 UTC, papafe approved these changes
LGTM

2024-10-01 13:42 UTC, merged