DOCSP-45715: Sealed class v3.0 changes
mongodb/docs-csharp pull request #345
Opened 2024-12-03 19:56 UTC by mcmorisi

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-golang/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-45715> and <https://jira.mongodb.org/browse/DOCSP-45716>

### Staging Links

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?
- [x] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-12-03 21:12 UTC, norareidy approved these changes
LGTM + one suggestion!

2024-12-03 21:12 UTC, norareidy commented on source/upgrade/v3.txt
> +  sealed. We recommend using the ``IMongoClient``, ``IMongoDatabase``, and
S: I'd update to active voice

```suggestion
- The driver seals all concrete serializers. To implement a custom serializer, implement the
  ``IBsonSerializer`` interface.

- The driver seals the ``MongoClient``, ``MongoDatabase``, and ``MongoCollection`` classes. We recommend using the ``IMongoClient``, ``IMongoDatabase``, and
```

2024-12-04 20:50 UTC, BorisDog requested changes

2024-12-04 20:50 UTC, BorisDog commented on source/upgrade/v3.txt
> +- The driver seals all concrete serializers. To implement a custom serializer, implement the
We had some questions of "why" classes got sealed.
It's worth adding a general comment followed by these concrete examples:
Something like "Some of the types that were not designed for extension via inheritance became sealed. Starting with 3.0 we recommend using "composition over inheritance" approach for extending the driver functionality."

2024-12-06 21:03 UTC, BorisDog approved these changes
LGTM

2024-12-06 21:22 UTC, merged