DOCSP-40654-sample-aggregation-operator
mongodb/docs-csharp pull request #360
Opened 2024-12-06 19:21 UTC by gmiller-mdb

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-golang/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-40654>

### Staging Links

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-12-06 21:16 UTC, mongoKart requested changes
nice work! a few small things that i'm happy to help on 👍

2024-12-10 14:53 UTC, gmiller-mdb commented on source/fundamentals/linq.txt
> +.. code-block:: csharp
I've done a couple of tests and I unfortunately do not think the work-around is very feasible- there is issues with the string conversion that requires me adding a bunch of extra methods that I don't think are very efficient.

2024-12-10 17:38 UTC, mongoKart approved these changes
LGTM. thanks for putting in the time and effort to investigate LINQ

2024-12-11 20:56 UTC, adelinowona requested changes

2024-12-11 20:56 UTC, adelinowona commented on source/fundamentals/linq.txt
> +   { "title" : "The Rains Came", "languages" : ["English"] }
The results from the code samples in this page seem to be using the `restaurants` collection from the `sample_restaurants` database. However, the results here seem to be from the `movies` collection in the `sample_mflix` database. You should update the results here.

2024-12-12 23:05 UTC, adelinowona approved these changes
LGTM

2024-12-16 18:06 UTC, merged