DOCSP-39938-libmongocrypt-bindindings
mongodb/docs-csharp pull request #366
Opened 2024-12-09 21:15 UTC by gmiller-mdb

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-golang/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-39938>

### Staging Links

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-12-09 21:22 UTC, gmiller-mdb commented
I am unsure how to made the 'libmongocrypt' heading smaller? I've tried various RST styles and it hasn't been a problem before.

2024-12-11 18:42 UTC, adelinowona requested changes

2024-12-11 18:42 UTC, adelinowona commented on source/fundamentals/encrypt-fields.txt
> +Libmongocrypt
You probably don't need the title anymore

2024-12-11 20:23 UTC, adelinowona requested changes
few more minor comments

2024-12-11 20:23 UTC, adelinowona commented on source/fundamentals/encrypt-fields.txt
> +To use CSFLE with the driver, you need to have the MongoDB.Driver.Encryption
Could you hyperlink Mongo.Driver.Encryption to its nuget page? Should be this https://www.nuget.org/packages/MongoDB.Driver.Encryption

2024-12-11 20:23 UTC, adelinowona commented on source/fundamentals/encrypt-fields.txt
> +You can find the instructions for downloading a pre-built binary libmongocrypt
downloading "a libmongocrypt library"

2024-12-11 20:23 UTC, adelinowona commented on source/fundamentals/encrypt-fields.txt
> +recommend manually installing the libmongocrypt library and specifying its path
replace path with "absolute path"

2024-12-11 20:59 UTC, adelinowona approved these changes
LGTM!

2024-12-11 21:44 UTC, adelinowona commented
Also, as a note, there's a typo in your PR title. bindindings -> bindings

2024-12-12 21:42 UTC, gmiller-mdb commented
hi @adelinowona , talked with my team and we decided to move this information into the server docs proper. thanks for all of your help!

2024-12-12 21:42 UTC, closed without merging